import { DrenagensController } from './controllers/drenagens.js';
import { DrenagensView } from './views/drenagens.js';
import { DrenagensModel } from './models/drenagens.js';
import { UnidadesHidrograficasController } from './controllers/unidades-hidrograficas.js';
import { UnidadesHidrograficasModel } from './models/unidades-hidrograficas.js';
import { UnidadesHidrograficasView } from './views/unidades-hidrograficas.js';
import {  createTBody, atualizeTBody  } from './views/elements.js';
import {Tabela} from './views/tabela.js';


let slider = tns({
  container: '.my-slider',
  items: 1,
  slideBy: 'page',
  autoplay: false
});

let outorgas = [
  {
    "attributes": {
      "OBJECTID": 1251,
      "VERIFICADO": "PENDENTE",
      "NUM_PROCES": "197000021/2013",
      "USUARIO": "JOHANES VIX",
      "CPF_CNPJ": "00080276172",
      "LOGRADOURO": "CHÁCARA Nº 18",
      "BAIRRO": "NÚCLEO RURAL MONJOLO",
      "RA": "RECANTO DAS EMAS",
      "ESTADO": "DF",
      "CEP": null,
      "LOG_CORRES": "CHÁCARA Nº 18",
      "BAIRRO_COR": "NÚCLEO RURAL MONJOLO",
      "RA_CID_COR": "RECANTO DAS EMAS",
      "ESTADO_COR": "DF",
      "CEP_CORRES": null,
      "CAIXA_POST": " ",
      "NOME_CONTA": "JOHANES VIX",
      "TELEFONE_1": "61985640224",
      "TELEFONE_2": "61996733620",
      "E_MAIL": " ",
      "TIPO_ATO": "REGISTRO",
      "TIPO_OUTOR": "REGISTRO DE USO",
      "SUBT_OUT": "REGULARIZAÇÃO",
      "NUM_ATO": "018/2015",
      "Data_pub_a": 1426042800000,
      "Data_venc_": null,
      "SITUACAO": "OUTORGADO",
      "TIPO_CAPTA": "SUPERFICIAL",
      "LOCAL_CAPT": "RESERVATÓRIO",
      "CORPO_HIDR": "NASCENTE",
      "BACIA": "RIO CORUMBÁ",
      "COD_UH": 25,
      "FORMA_CAPT": "GRAVIDADE",
      "EXISTE_BAR": " ",
      "FINALIDA_1": "IRRIGAÇÃO",
      "SUBFINAL_1": " ",
      "VAZAO_1": 0,
      "FINALIDA_2": "OUTROS",
      "SUBFINAL_2": " ",
      "VAZAO_2": 0,
      "FINALIDA_3": "ABASTECIMENTO HUMANO",
      "SUBFINAL_3": " ",
      "VAZAO_3": 2200,
      "FINALIDA_4": "CRIAÇÃO DE ANIMAIS",
      "SUBFINAL_4": null,
      "VAZAO_4": 300,
      "FINALIDA_5": null,
      "SUBFINAL_5": " ",
      "VAZAO_5": 0,
      "METODO_IRR": null,
      "AREA_IRRI": 0,
      "AREA_CONTR": 0,
      "TAM_PROPIE": 58,
      "Q_SEG_JAN": 0.7,
      "Q_SEG_FEV": 0.7,
      "Q_SEG_MAR": 0.7,
      "Q_SEG_ABR": 0.7,
      "Q_SEG_MAI": 0.7,
      "Q_SEG_JUN": 0.7,
      "Q_SEG_JUL": 0.7,
      "Q_SEG_AGO": 0.7,
      "Q_SEG_SET": 0.7,
      "Q_SEG_OUT": 0.7,
      "Q_SEG_NOV": 0.7,
      "Q_SEG_DEZ": 0.7,
      "TEMP_CAP_1": 24,
      "TEMP_CAP_2": 24,
      "TEMP_CAP_3": 24,
      "TEMP_CAP_4": 24,
      "TEMP_CAP_5": 24,
      "TEMP_CAP_6": 24,
      "TEMP_CAP_7": 24,
      "TEMP_CAP_8": 24,
      "TEMP_CAP_9": 24,
      "TEMP_CAP10": 24,
      "TEMP_CAP11": 24,
      "TEMP_CAP12": 24,
      "DIAS_JAN": 30,
      "DIAS_FEV": 28,
      "DIAS_MAR": 30,
      "DIAS_ABR": 31,
      "DIAS_MAI": 30,
      "DIAS_JUN": 31,
      "DIAS_JUL": 30,
      "DIAS_AGO": 31,
      "DIAS_SET": 30,
      "DIAS_OUT": 31,
      "DIAS_NOV": 30,
      "DIAS_DEZ": 31,
      "VolMax_JAN": null,
      "VolMax_FEV": null,
      "VolMax_MAR": null,
      "VolMax_ABR": null,
      "VolMax_MAI": null,
      "VolMax_JUN": null,
      "VolMax_JUL": null,
      "VolMax_AGO": null,
      "VolMax_SET": null,
      "VolMax_OUT": null,
      "VolMax_NOV": null,
      "VolMax_DEZ": null,
      "DOMINIO": "ESTADUAL",
      "HIDROMETRO": null,
      "REUSO": null,
      "OBSERVACAO": "SEM ARQUIVO DIGITAL DE REQUERIMENTO",
      "Latitude": -15.937672,
      "Longitude": -48.07584
    }
  },
  {
    "attributes": {
      "OBJECTID": 43601,
      "VERIFICADO": "OK",
      "NUM_PROCES": "19700000396/2018",
      "USUARIO": "NORTE E SUL HOTELARIA LTDA",
      "CPF_CNPJ": "03706035000139",
      "LOGRADOURO": "NÚCLEO RURAL MONJOLO, CHÁCARA Nº12",
      "BAIRRO": "MONJOLO",
      "RA": "RECANTO DAS EMAS",
      "ESTADO": "DF",
      "CEP": "72600000",
      "LOG_CORRES": "SH LOTE 04, 1º PAVIMENTO, SETOR COMERCIAL",
      "BAIRRO_COR": null,
      "RA_CID_COR": "GAMA",
      "ESTADO_COR": "DF",
      "CEP_CORRES": "72405604",
      "CAIXA_POST": null,
      "NOME_CONTA": "MANOEL TEODORO FROTA",
      "TELEFONE_1": "61996488157",
      "TELEFONE_2": null,
      "E_MAIL": "MANOELFROTA86@GMAIL.COM",
      "TIPO_ATO": "DESPACHO",
      "TIPO_OUTOR": "OUTORGA DE DIREITO DE USO",
      "SUBT_OUT": "REGULARIZAÇÃO",
      "NUM_ATO": "161/2018",
      "Data_pub_a": 1520823600000,
      "Data_venc_": 1836442800000,
      "SITUACAO": "OUTORGADO",
      "TIPO_CAPTA": "SUPERFICIAL",
      "LOCAL_CAPT": "NASCENTE",
      "CORPO_HIDR": "CÓRREGO MONJOLO",
      "BACIA": "RIO CORUMBÁ",
      "COD_UH": 25,
      "FORMA_CAPT": "BOMBEAMENTO",
      "EXISTE_BAR": null,
      "FINALIDA_1": "IRRIGAÇÃO",
      "SUBFINAL_1": "POMAR",
      "VAZAO_1": 19200,
      "FINALIDA_2": "CRIAÇÃO DE ANIMAIS",
      "SUBFINAL_2": "BOVINOS",
      "VAZAO_2": 2400,
      "FINALIDA_3": null,
      "SUBFINAL_3": null,
      "VAZAO_3": null,
      "FINALIDA_4": null,
      "SUBFINAL_4": null,
      "VAZAO_4": null,
      "FINALIDA_5": null,
      "SUBFINAL_5": null,
      "VAZAO_5": null,
      "METODO_IRR": null,
      "AREA_IRRI": 0.4,
      "AREA_CONTR": 208,
      "TAM_PROPIE": null,
      "Q_SEG_JAN": 1,
      "Q_SEG_FEV": 1,
      "Q_SEG_MAR": 1,
      "Q_SEG_ABR": 1,
      "Q_SEG_MAI": 1,
      "Q_SEG_JUN": 1,
      "Q_SEG_JUL": 1,
      "Q_SEG_AGO": 1,
      "Q_SEG_SET": 1,
      "Q_SEG_OUT": 1,
      "Q_SEG_NOV": 1,
      "Q_SEG_DEZ": 1,
      "TEMP_CAP_1": 6,
      "TEMP_CAP_2": 6,
      "TEMP_CAP_3": 6,
      "TEMP_CAP_4": 6,
      "TEMP_CAP_5": 6,
      "TEMP_CAP_6": 6,
      "TEMP_CAP_7": 6,
      "TEMP_CAP_8": 6,
      "TEMP_CAP_9": 6,
      "TEMP_CAP10": 6,
      "TEMP_CAP11": 6,
      "TEMP_CAP12": 6,
      "DIAS_JAN": 31,
      "DIAS_FEV": 28,
      "DIAS_MAR": 31,
      "DIAS_ABR": 30,
      "DIAS_MAI": 31,
      "DIAS_JUN": 30,
      "DIAS_JUL": 31,
      "DIAS_AGO": 31,
      "DIAS_SET": 30,
      "DIAS_OUT": 31,
      "DIAS_NOV": 30,
      "DIAS_DEZ": 31,
      "VolMax_JAN": null,
      "VolMax_FEV": null,
      "VolMax_MAR": null,
      "VolMax_ABR": null,
      "VolMax_MAI": null,
      "VolMax_JUN": null,
      "VolMax_JUL": null,
      "VolMax_AGO": null,
      "VolMax_SET": null,
      "VolMax_OUT": null,
      "VolMax_NOV": null,
      "VolMax_DEZ": null,
      "DOMINIO": "ESTADUAL",
      "HIDROMETRO": null,
      "REUSO": null,
      "OBSERVACAO": null,
      "Latitude": -15.941602,
      "Longitude": -48.053817
    }
  },
];

let tabela = new Tabela('out_secao');
tabela.atualizeTBody(outorgas);
//let tbody = createTBody('out_secao');
//atualizeTBody(tbody, outorgas);

let UnidadesHidrograficas = new UnidadesHidrograficasModel();

new DrenagensController(new DrenagensModel(), new DrenagensView(), UnidadesHidrograficas);
new UnidadesHidrograficasController(UnidadesHidrograficas, new UnidadesHidrograficasView());












